# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[hostname]
ssh_only = false
format = 'on [$hostname](bold red) '
trim_at = "."
disabled = false

[nix_shell]
symbol = "❄️"
format = 'via [$symbol $state](bold blue) '

